import { useUser } from "@auth0/nextjs-auth0/client";
import Header from "../components/header/Header";
import {
	Avatar,
	Box,
	Button,
	Card,
	CardBody,
	CardHeader,
	Code,
	Container,
	Heading,
	Stack,
	StackDivider,
	Text,
} from "@chakra-ui/react";
import Head from "next/head";
import Body from "../components/body/Body";
import { useRouter } from "next/router";

export default function Home() {
	const router = useRouter();

	const { user } = useUser();

	return (
		<Box w='full'>
			<Head>
				<title>Our Token Website</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Header />
			<Body />

		</Box>
	);
}
