import { useUser } from "@auth0/nextjs-auth0/client";
import Header from "../components/header/Header";
import {
	Avatar,
	Box,
	Button,
	Card,
	CardBody,
	CardHeader,
	Code,
	Container,
	Heading,
	Stack,
	StackDivider,
	Text,
} from "@chakra-ui/react";
import Head from "next/head";
import Body from "../components/body/Body";
import { useRouter } from "next/router";
import { useEffect, useState } from 'react';


// export async function getStaticProps() {
// 	const response = await fetch('/api/test_request');
// 	const responseData = await response.json();
// 	console.log(responseData);
// 	return {
// 		props: { home: responseData.data }
// 	}
// }

export default function Home() {
	const router = useRouter();
	const { user } = useUser();
	const [data, setData] = useState(null);

	useEffect(() => {
		const fetchData = async () => {
			try {
				const response = await fetch('/api/test_request');
				const responseData = await response.json();
				console.log(responseData);
				setData(responseData)
			} catch (error) {
				console.error('Error fetching data:', error);
			}
		};

		fetchData();
	}, []);

	return (
		<Box w='full'>
			{data ? (
				<div>
					<h1>{data['data']['hello']}</h1>
					{/* <h1>{data.message}</h1> */}
				</div>
			) : (
				<h1>No Data...</h1>
			)}
			<Head>
				<title>Unopass</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Header />
			<Body />

		</Box>
	);
}
